apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local: 
    push: false
  artifacts:
    - image: sajeebxn/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # - src: "src/*"
          - src: "src/**/*.ts"
            dest: .
    - image: sajeebxn/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          # - src: "src/*"
          - src: "**/*.js"
            dest: .
    - image: sajeebxn/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .